# Generated by Django 3.2.3 on 2024-10-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='contacts',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='assignedTo', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
