# Generated by Django 3.2.3 on 2024-11-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241105_2000'),
    ]

    operations = [
    ]
