# Generated by Django 3.2.3 on 2024-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20241108_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to='api.Contacts'),
        ),
    ]
