# Generated by Django 3.2.3 on 2024-11-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_auth', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
