# Generated by Django 3.2.3 on 2024-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgecolor', models.CharField(max_length=8)),
                ('initials', models.CharField(max_length=2)),
                ('register', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('priority', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('dueDate', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('assignedTo', models.ManyToManyField(blank=True, related_name='tasks', to='apis.Contacts')),
                ('subtasks', models.ManyToManyField(blank=True, related_name='tasks', to='apis.Subtasks')),
            ],
        ),
    ]
